### ISSUE TITLE
Remove "reply" "share" and "link" button (for now)

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/Vision#16]
## User Story:
I terms of focussing on what is important (right now), we should remove the ability to share and discuss about Webmarks.

## Why?
Because there is no profile system implemented in H.
Means, this needs some further thinking. 
Making discussions and sharing of those bookmarks possible would complicate too much.
This feature will be enabled again as soon as we have the user profiles ready, so that people can identify each other.

## Details of Execution:
Just remove the "reply" and "link" button from every Webmark and also remove the "View group activity and invite others" Label in the group section.

## MOCKUPS:
https://drive.google.com/drive/u/0/folders/0BwhDeiu80lkjYmYycTlzTkExX0U

[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/82254329257792/f
---[aa]

**Comment by lwm** [comment]
I am not sure this is valid any more. The hypothesis team will never agree to remove features that already exist and serve their user base. Either we develop them more to suit our needs as well or we keep them.

> Just remove the "reply" and "link" button from every Webmark

Check out [this annotation](https://hypothes.is/a/quL8BT67STO0De44e1VI1w). It's basic but it still useful? A user can create a perma link to their annotation and other registered users can comment on it. Their username identifies them.

> Making discussions and sharing of those bookmarks possible would complicate too much.

This is already happening though.

Are you looking for better improved user profiles? If that is the case, maybe we should close this and re formulate. It is also worth noting that improved user interaction is heavily featured in the [Hypothesis/h roadmap](https://hypothes.is/roadmap/). So these things are coming anyway.

Thoughts?

**Comment by oliversauter** [comment]
Can we remove them with the modular way you were talking about?
You talked about the switches, where users can decide which features to turn off and on, why not developing a module, that does just that but is disabled from the start?

**Comment by lwm** [comment]
That would be possible, but this naturally introduces more logic for configuring on/off. This should be minimized for cases where things should definitely be pluggable. I can't see a reason for these minimal user features being pluggable.

> I terms of focussing on what is important (right now), we should remove the ability to share and discuss about Webmarks.

Why? Because:

> Because there is no profile system implemented in H.

But there is (albeit minimal!). So, that is why I can't understand this one.

**Comment by oliversauter** [comment]
> But there is (albeit minimal!). So, that is why I can't understand this one.
Yeah it is really minimal, the only thing is basically a username.

My idea was that the profiles may be underdeveloped to make the sharing transparent enough for users. But now as I think about it, who really cares? If we gradually introduce new features to the profiles its cool anyway.
At least it is working and you see who commented on your Webmarks.

And yeah, we should reduce the work to a minimum. :+1:

**Comment by lwm** [comment]
> If we gradually introduce new features to the profiles its cool anyway.

Agreed. I think this is really what is being asked for by this issue but will need to be re formulated in another. Or when we get a clearer idea of what is needed. So I will close this off.
